### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by JotaVeUltra**
## Description

Write a brief and explicative description of your pull request.

## Your checklist for this pull request

:rotating_light: Please review this items for a good pull request. :four_leaf_clover:

1. I've read the project's [Contributing Guidelines](../CONTRIBUTING.md)
1. My commits are well written and follow [pagarme/git-style-guide](https://github.com/pagarme/git-style-guide)
1. My changes are well covered by **tests** and **logs**
1. I've updated the project docs (if needed)
1. I fell safe about this implementation
1. I feel comfortable with the code I wrote, and I'm not ashamed to show it to my friends

In a good pull request, everything above is true :relaxed:

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 958a76086d0db2d1f34f76feaa66dad773b40d17
  * Commits must be in the following format: **%{scope}: %{description}**

Check out our Git Style Guide here: https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by jeanaugustoos** [comment]
Hi, @JotaVeUltra!

First of all, thanks for your contribution.

I'd like to ask you to check our [Git Style Guide](https://github.com/pagarme/git-style-guide) and reword the commit 958a76086d0db2d1f34f76feaa66dad773b40d17. Also, it's very important write a brief description about your changes.

**Comment by Thor99** [comment]
Hi @JotaVeUltra! Do you intend to proceed with this PR?

**Comment by JotaVeUltra** [comment]
I don't intend.

I will close the pull request.

**Pull request closed without merging**
