### PR TITLE
Fix provider error

### PR DESCRIPTION
**Pull request by otaviopace**
## Description

Write a brief and explicative description of your pull request.

## Your checklist for this pull request

:rotating_light: Please review this items for a good pull request. :four_leaf_clover:

1. I've read the project's [Contributing Guidelines](../CONTRIBUTING.md)
1. My commits are well written and follow [pagarme/git-style-guide](https://github.com/pagarme/git-style-guide)
1. My changes are well covered by **tests** and **logs**
1. I've updated the project docs (if needed)
1. I fell safe about this implementation
1. I feel comfortable with the code I wrote, and I'm not ashamed to show it to my friends

In a good pull request, everything above is true :relaxed:

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: dc8967cca160e27b25bf293408a5dfceedf9c295
  * Your commit message body contains a line that is longer than 72 characters

Check out our Git Style Guide here: https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by grvcoelho** [comment]
Hi @otaviopace :) thanks a lot for your PR.

Would you remind rebasing it with the master to update your branch?

**Comment by otaviopace** [comment]
No problem! I have done the rebase :)

**Comment by grvcoelho** [comment]
Nice! Thanks :smile:

**Pull request merged**
